In [1]:
import pandas as pd
import numpy as np

In [13]:
columns = [
    'CRT_KANSYO',
    'NTZK_TRNSPTMTHDFORSRCHCODE',
    'NTZK_DCLRTNKINDCODE',
    'NTZK_RGSTDDATE',
    'NTZK_RGSTDTIME',
    'NTZK_CNTRYCODE',
    'NTZK_UNLOADINGPORTCODE',
    'NTZK_LOADINGLOCTNCODE',
    'NTZK_PYMTTERM',
    'NTZK_TTLTAXVAL',
    'NTZK_TTLPAYABLETAX',
    'NTZR_HSCODE',
    'NTZR_QTY_1',
    'NTZR_QTYUNITCODE_1',
    'NTZR_IMPTAXRATE',
    'NTZR_IMPTAXAMNT',
    'NTZR_ORIGINPLCCODE',
    'INPUT'
]
df = pd.read_csv('data/Dữ liệu test.txt', nrows=100000, delimiter='\t', usecols=columns,
                 dtype={'NTZR_HSCODE': str, 'NTZK_RGSTDDATE': str, 'NTZK_RGSTDTIME': str})
# df.to_csv('data/apriori.csv', index=False)
df1 = df.query('INPUT==0').sample(frac=0.1, random_state=7)
df2 = df.query('INPUT==1')
df = df1.append(df2)
df = df.astype({'INPUT': str})
df.head()

,CRT_KANSYO,NTZK_TRNSPTMTHDFORSRCHCODE,NTZK_DCLRTNKINDCODE,NTZK_RGSTDDATE,NTZK_RGSTDTIME,NTZK_CNTRYCODE,NTZK_UNLOADINGPORTCODE,NTZK_LOADINGLOCTNCODE,NTZK_PYMTTERM,NTZK_TTLTAXVAL,NTZK_TTLPAYABLETAX,NTZR_HSCODE,NTZR_QTY_1,NTZR_QTYUNITCODE_1,NTZR_IMPTAXRATE,NTZR_IMPTAXAMNT,NTZR_ORIGINPLCCODE,INPUT
35898,03NK,O,A12,20200104,143346,VN,VNXFH,VNZZZ,KC,3.155070e+07,NaN,48191000,30.0,PCE,NaN,NaN,VN,0
40375,03NK,O,E11,20200109,142008,VN,VNXFH,VNZZZ,KC,2.822824e+08,NaN,39269099,14400.0,PCE,NaN,NaN,VN,0
53403,47XE,O,E15,20200106,145718,VN,VNZZZ,VNZZZ,TTR,2.865361e+08,NaN,72119099,250.8,KGM,NaN,NaN,VN,0
11361,01PR,O,A12,20200106,102305,VN,VNZZZ,VNZZZ,KC,6.048526e+08,NaN,76169990,5.0,PCE,NaN,NaN,VN,0
70181,01PR,O,E15,20200107,084934,VN,VNXRL,VNZZZ,KC,1.451513e+09,NaN,48089090,82.0,PCE,NaN,NaN,VN,0

In [3]:
dfProcessed = df.copy()

dfProcessed['NTZR_HSCODE_2'] = dfProcessed.NTZR_HSCODE.str[0:2]
# dfProcessed['NTZR_HSCODE_4'] = dfProcessed.NTZR_HSCODE.str[0:4]
# dfProcessed['NTZR_HSCODE_6'] = dfProcessed.NTZR_HSCODE.str[0:6]
# dfProcessed['NTZR_HSCODE_8'] = dfProcessed.NTZR_HSCODE.str[0:8]

# dfProcessed['NTZK_RGSTDMONTH'] = dfProcessed.NTZK_RGSTDDATE.str[4:6]
dfProcessed['NTZK_RGSTDHOUR'] = dfProcessed.NTZK_RGSTDTIME.str[0:2]

labels = dfProcessed.NTZK_TTLTAXVAL.quantile(np.linspace(0,1,11)).values.astype(int)[1:]
dfProcessed['NTZK_TTLTAXVAL'] = pd.qcut(dfProcessed.NTZK_TTLTAXVAL, q=10, labels=labels)

columns = [
    'CRT_KANSYO',
    'NTZK_TRNSPTMTHDFORSRCHCODE',
    'NTZK_DCLRTNKINDCODE',
    'NTZK_UNLOADINGPORTCODE',
    'NTZK_PYMTTERM',
    'NTZK_TTLTAXVAL',
    'NTZR_HSCODE_2',
    'NTZK_RGSTDHOUR',
    'INPUT',
]
dfProcessed = dfProcessed[columns]
dfProcessed = pd.get_dummies(dfProcessed)

dfProcessed.columns.tolist()
dfProcessed = dfProcessed.astype(bool)
dfProcessed.head()

,CRT_KANSYO_01IK,CRT_KANSYO_01M1,CRT_KANSYO_01NV,CRT_KANSYO_01PJ,CRT_KANSYO_01PQ,CRT_KANSYO_01PR,CRT_KANSYO_02F1,CRT_KANSYO_02F2,CRT_KANSYO_02F3,CRT_KANSYO_02PG,...,NTZK_RGSTDHOUR_16,NTZK_RGSTDHOUR_17,NTZK_RGSTDHOUR_18,NTZK_RGSTDHOUR_19,NTZK_RGSTDHOUR_20,NTZK_RGSTDHOUR_21,NTZK_RGSTDHOUR_22,NTZK_RGSTDHOUR_23,INPUT_0,INPUT_1
35898,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
40375,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
53403,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
11361,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
70181,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [11]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
dfFreq = apriori(dfProcessed, use_colnames=True, min_support=0.8)
dfFreq

    support                                 itemsets
0  0.995121           (NTZK_TRNSPTMTHDFORSRCHCODE_O)
1  0.995221                                (INPUT_0)
2  0.990342  (NTZK_TRNSPTMTHDFORSRCHCODE_O, INPUT_0)

In [12]:
dfRules = dfFreq[dfFreq.itemsets.astype(str).str.contains('INPUT_0')]
dfRules = association_rules(dfRules, support_only=False, metric='confidence', min_threshold=0.5)
dfRules = dfRules[dfRules.consequents=={'INPUT_0'}]
dfRules

KeyError: "frozenset({'NTZK_TRNSPTMTHDFORSRCHCODE_O'})You are likely getting this error because the DataFrame is missing  antecedent and/or consequent  information. You can try using the  `support_only=True` option"

# mlextend

In [5]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [6]:
apriori(df)

    support   itemsets
0       0.8        (3)
1       1.0        (5)
2       0.6        (6)
3       0.6        (8)
4       0.6       (10)
5       0.8     (3, 5)
6       0.6     (8, 3)
7       0.6     (5, 6)
8       0.6     (8, 5)
9       0.6    (10, 5)
10      0.6  (8, 3, 5)

# apyori

In [116]:
from apyori import apriori
rule = list(apriori(dataset))

In [129]:
rule[-1][2]

[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Kidney Beans', 'Milk', 'Onion', 'Yogurt', 'Eggs', 'Nutmeg'}), confidence=0.2, lift=1.0),
 OrderedStatistic(items_base=frozenset({'Eggs'}), items_add=frozenset({'Onion', 'Yogurt', 'Nutmeg', 'Milk', 'Kidney Beans'}), confidence=0.25, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Kidney Beans'}), items_add=frozenset({'Onion', 'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), confidence=0.2, lift=1.0),
 OrderedStatistic(items_base=frozenset({'Milk'}), items_add=frozenset({'Onion', 'Yogurt', 'Eggs', 'Nutmeg', 'Kidney Beans'}), confidence=0.33333333333333337, lift=0.8333333333333334),
 OrderedStatistic(items_base=frozenset({'Nutmeg'}), items_add=frozenset({'Onion', 'Yogurt', 'Eggs', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Onion'}), items_add=frozenset({'Kidney Beans', 'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt'}), items_add=frozenset({'Onion', 'Eggs', 'Nutmeg', 'Milk', 'Kidney Beans'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Nutmeg', 'Milk', 'Onion'}), confidence=0.25, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Milk'}), items_add=frozenset({'Nutmeg', 'Kidney Beans', 'Yogurt', 'Onion'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg'}), items_add=frozenset({'Yogurt', 'Kidney Beans', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Onion'}), items_add=frozenset({'Yogurt', 'Nutmeg', 'Milk', 'Kidney Beans'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs'}), items_add=frozenset({'Nutmeg', 'Kidney Beans', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Onion'}), confidence=0.33333333333333337, lift=0.8333333333333334),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Onion', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Nutmeg', 'Milk', 'Onion'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Milk'}), items_add=frozenset({'Yogurt', 'Eggs', 'Kidney Beans', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Onion', 'Milk'}), items_add=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Kidney Beans'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Milk'}), items_add=frozenset({'Nutmeg', 'Eggs', 'Kidney Beans', 'Onion'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Onion'}), items_add=frozenset({'Yogurt', 'Eggs', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg'}), items_add=frozenset({'Eggs', 'Kidney Beans', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Onion'}), items_add=frozenset({'Eggs', 'Nutmeg', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Nutmeg', 'Onion'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Nutmeg', 'Milk'}), confidence=0.33333333333333337, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Kidney Beans'}), items_add=frozenset({'Nutmeg', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Milk'}), items_add=frozenset({'Yogurt', 'Kidney Beans', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Onion', 'Milk'}), items_add=frozenset({'Yogurt', 'Nutmeg', 'Kidney Beans'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Milk'}), items_add=frozenset({'Nutmeg', 'Kidney Beans', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Onion'}), items_add=frozenset({'Yogurt', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Nutmeg'}), items_add=frozenset({'Kidney Beans', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Onion'}), items_add=frozenset({'Nutmeg', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Onion', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Nutmeg'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Nutmeg', 'Onion'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs', 'Milk'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Nutmeg', 'Milk'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Nutmeg', 'Onion', 'Milk'}), items_add=frozenset({'Yogurt', 'Eggs', 'Kidney Beans'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Milk'}), items_add=frozenset({'Eggs', 'Kidney Beans', 'Onion'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Onion', 'Milk'}), items_add=frozenset({'Eggs', 'Nutmeg', 'Kidney Beans'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Onion'}), items_add=frozenset({'Eggs', 'Milk', 'Kidney Beans'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Onion', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Nutmeg'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Nutmeg', 'Onion'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Milk'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Kidney Beans'}), items_add=frozenset({'Milk', 'Onion'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Nutmeg', 'Milk'}), confidence=0.5, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Eggs', 'Nutmeg', 'Onion', 'Milk'}), items_add=frozenset({'Yogurt', 'Kidney Beans'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), items_add=frozenset({'Kidney Beans', 'Onion'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Onion', 'Milk'}), items_add=frozenset({'Nutmeg', 'Kidney Beans'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Eggs', 'Nutmeg', 'Onion'}), items_add=frozenset({'Milk', 'Kidney Beans'}), confidence=0.5, lift=0.8333333333333334),
 OrderedStatistic(items_base=frozenset({'Onion', 'Nutmeg', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Yogurt', 'Eggs'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Onion'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Onion', 'Milk', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Nutmeg'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Onion', 'Kidney Beans'}), items_add=frozenset({'Eggs', 'Milk'}), confidence=0.5, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Yogurt', 'Nutmeg', 'Onion', 'Milk'}), items_add=frozenset({'Eggs', 'Kidney Beans'}), confidence=1.0, lift=1.25),
 OrderedStatistic(items_base=frozenset({'Onion', 'Kidney Beans', 'Eggs', 'Nutmeg', 'Milk'}), items_add=frozenset({'Yogurt'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Kidney Beans', 'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), items_add=frozenset({'Onion'}), confidence=1.0, lift=1.6666666666666667),
 OrderedStatistic(items_base=frozenset({'Onion', 'Yogurt', 'Eggs', 'Kidney Beans', 'Milk'}), items_add=frozenset({'Nutmeg'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'Onion', 'Yogurt', 'Eggs', 'Nutmeg', 'Kidney Beans'}), items_add=frozenset({'Milk'}), confidence=0.5, lift=0.8333333333333334),
 OrderedStatistic(items_base=frozenset({'Onion', 'Yogurt', 'Eggs', 'Nutmeg', 'Milk'}), items_add=frozenset({'Kidney Beans'}), confidence=1.0, lift=1.0),
 OrderedStatistic(items_base=frozenset({'Onion', 'Yogurt', 'Kidney Beans', 'Nutmeg', 'Milk'}), items_add=frozenset({'Eggs'}), confidence=1.0, lift=1.25)]

In [140]:
dfOut = pd.DataFrame(output)
dfOut = dfOut.explode('ordered_statistics')
dfOut[['antecedent', 'consequent', 'confidence', 'lift']] = dfOut.ordered_statistics.apply(pd.Series)
for i in ['items', 'antecedent', 'consequent']:
    dfOut[i] = dfOut[i].str.join(',')
dfOut = dfOut.drop(columns=['ordered_statistics'])
dfOut

,items,support,antecedent,consequent,confidence,lift
0,Eggs,0.8,,Eggs,0.80,1.00
1,Kidney Beans,1.0,,Kidney Beans,1.00,1.00
2,Milk,0.6,,Milk,0.60,1.00
3,Onion,0.6,,Onion,0.60,1.00
4,Yogurt,0.6,,Yogurt,0.60,1.00
5,"Eggs,Kidney Beans",0.8,,"Eggs,Kidney Beans",0.80,1.00
5,"Eggs,Kidney Beans",0.8,Eggs,Kidney Beans,1.00,1.00
5,"Eggs,Kidney Beans",0.8,Kidney Beans,Eggs,0.80,1.00
6,"Eggs,Onion",0.6,,"Eggs,Onion",0.60,1.00
6,"Eggs,Onion",0.6,Eggs,Onion,0.75,1.25
6,"Eggs,Onion",0.6,Onion,Eggs,1.00,1.25
7,"Milk,Kidney Beans",0.6,,"Kidney Beans,Milk",0.60,1.00
7,"Milk,Kidney Beans",0.6,Kidney Beans,Milk,0.60,1.00
7,"Milk,Kidney Beans",0.6,Milk,Kidney Beans,1.00,1.00
8,"Onion,Kidney Beans",0.6,,"Kidney Beans,Onion",0.60,1.00
8,"Onion,Kidney Beans",0.6,Kidney Beans,Onion,0.60,1.00
8,"Onion,Kidney Beans",0.6,Onion,Kidney Beans,1.00,1.00
9,"Yogurt,Kidney Beans",0.6,,"Yogurt,Kidney Beans",0.60,1.00
9,"Yogurt,Kidney Beans",0.6,Kidney Beans,Yogurt,0.60,1.00
9,"Yogurt,Kidney Beans",0.6,Yogurt,Kidney Beans,1.00,1.00
10,"Eggs,Onion,Kidney Beans",0.6,,"Eggs,Kidney Beans,Onion",0.60,1.00
10,"Eggs,Onion,Kidney Beans",0.6,Eggs,"Kidney Beans,Onion",0.75,1.25
10,"Eggs,Onion,Kidney Beans",0.6,Kidney Beans,"Eggs,Onion",0.60,1.00
10,"Eggs,Onion,Kidney Beans",0.6,Onion,"Eggs,Kidney Beans",1.00,1.25
10,"Eggs,Onion,Kidney Beans",0.6,"Eggs,Kidney Beans",Onion,0.75,1.25
10,"Eggs,Onion,Kidney Beans",0.6,"Eggs,Onion",Kidney Beans,1.00,1.00
10,"Eggs,Onion,Kidney Beans",0.6,"Onion,Kidney Beans",Eggs,1.00,1.25

In [148]:
dfOut.query("antecedent != '' & consequent == 'Milk'")

               items  support    antecedent consequent  confidence  lift
7  Milk,Kidney Beans      0.6  Kidney Beans       Milk         0.6   1.0

# other

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/BejaminNaibei/dataset/main/Market_Basket_Optimisation.csv', header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
np.set_printoptions(precision=4, suppress=True)

In [20]:
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target
XTrain, XTest, yTrain, yTest = train_test_split(X, y, test_size=0.2, random_state=7)

In [21]:
model = DecisionTreeClassifier()
model = model.fit(XTrain, yTrain)

In [27]:
model.decision_path(XTrain).toarray()

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [28]:
20/14000

0.0014285714285714286